### ISSUE TITLE
Bug in "mydistance" function

### ISSUE THREAD

**Issue by myhussien** [glisanti/CLEAR-MOT#1]
The readme says the groundTruth boxes are in the form [tl.x tl.y br.x br.y] , however, the my distance function extract Width and Height directly from the elements instead of computing the actual width and height.

==== Error lines =====
woT =  target.bbox(3)
hoT =  target.bbox(4)
===== Possible Fix ======
woT =  target.bbox(3)-target.bbox(1);
hoT =  target.bbox(4)-target.bbox(2);

Best,
MYH

**Comment by iacopomasi** [comment]
Hey,
I see only now your message. I think the "bug" is the documentation because we parametrized the bbox with [x y w h] actually. I will update the docs.

**Comment by iacopomasi** [comment]
Hey,
I see only now your message. I think the "bug" is the documentation because we parametrized the bbox in the ground-truth as [x y w h] actually. I will update the docs.
